"""ORM models. Import everything here so Alembic autogenerate and metadata see every table."""

from gtmos.models.base import Base
from gtmos.models.core import User, Workspace
from gtmos.models.crm import (
    Account,
    AccountContactRole,
    Activity,
    Contact,
    Engagement,
    Opportunity,
    PipelineStage,
    StageTransition,
)
from gtmos.models.intelligence import (
    EnrichmentAttempt,
    EnrichmentRun,
    FieldProvenance,
    ICPProfile,
    ICPScore,
    ResearchEvidence,
    ResearchReport,
    ScoreComponent,
    Signal,
    SignalType,
)
from gtmos.models.ops import (
    AuditEvent,
    DataQualityIssue,
    ExternalRecord,
    Integration,
    IntegrationSync,
    RoutingDecision,
    RoutingRule,
    SimulatedCrmObject,
    WebhookEvent,
    Workflow,
    WorkflowRun,
    WorkflowStepRun,
)
from gtmos.models.outbound import (
    Campaign,
    Experiment,
    ExperimentAssignment,
    ExperimentOutcome,
    ExperimentVariant,
    MessageDraft,
    Sequence,
    SequenceStep,
)

__all__ = [
    "Account",
    "AccountContactRole",
    "Activity",
    "AuditEvent",
    "Base",
    "Campaign",
    "Contact",
    "DataQualityIssue",
    "Engagement",
    "EnrichmentAttempt",
    "EnrichmentRun",
    "Experiment",
    "ExperimentAssignment",
    "ExperimentOutcome",
    "ExperimentVariant",
    "ExternalRecord",
    "FieldProvenance",
    "ICPProfile",
    "ICPScore",
    "Integration",
    "IntegrationSync",
    "MessageDraft",
    "Opportunity",
    "PipelineStage",
    "ResearchEvidence",
    "ResearchReport",
    "RoutingDecision",
    "RoutingRule",
    "ScoreComponent",
    "Sequence",
    "SequenceStep",
    "Signal",
    "SignalType",
    "SimulatedCrmObject",
    "StageTransition",
    "User",
    "WebhookEvent",
    "Workflow",
    "WorkflowRun",
    "WorkflowStepRun",
    "Workspace",
]
