"""python -m gtmos.backtest [--json] [--out PATH]

Renders the scoring backtest as markdown so the result can be committed, diffed between ICP versions,
and reviewed without running the app. Reads only; it never writes to the database.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from sqlalchemy import select

from gtmos.db import session_scope
from gtmos.models import Workspace
from gtmos.services import scoring_eval


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _bucket_table(buckets: list[dict[str, Any]], first_col: str) -> list[str]:
    out = [
        f"| {first_col} | Accounts | Converted | Rate | 95% CI | Lift |",
        "| --- | ---: | ---: | ---: | :---: | ---: |",
    ]
    for b in buckets:
        flag = " ⚠︎" if b["small_sample"] else ""
        out.append(
            f"| {b['label']}{flag} | {b['n']} | {b['positives']} | {_pct(b['rate'])} | "
            f"{_pct(b['ci_low'])}–{_pct(b['ci_high'])} | {b['lift']:.2f}× |"
        )
    return out


def render(report: dict[str, Any]) -> str:
    pop = report["population"]
    lines = [
        "# Scoring backtest",
        "",
        "Generated by `python -m gtmos.backtest` against the demo dataset. Every number below is "
        "reproducible from the seed; none of it is evidence about the real world.",
        "",
        "## Population",
        "",
        f"- Scored accounts: **{pop['scored_accounts']}**",
        f"- Ever contacted: **{pop['contacted']}**",
        f"- Evaluated (contacted, not excluded): **{pop['evaluated']}**",
        f"- Excluded from ranking (grade X): **{pop['excluded_from_ranking']}**",
        "",
        pop["note"],
        "",
        "## Grade distribution",
        "",
        "| Grade | Accounts | Share |",
        "| --- | ---: | ---: |",
    ]
    lines += [f"| {g['grade']} | {g['accounts']} | {_pct(g['share'])} |" for g in report["grade_distribution"]]

    for _key, o in report["outcomes"].items():
        lines += ["", f"## Outcome: {o['label']}", "", f"_{o['definition']}_", "", "### By grade", ""]
        lines += _bucket_table(o["by_grade"], "Grade")
        lines += ["", "### By score variant", ""]
        lines += ["| Variant | AUC | 95% CI | Leakage |", "| --- | ---: | :---: | --- |"]
        for v in o["variants"].values():
            ci = v["auc_ci"]
            ci_text = f"{ci[0]:.3f}–{ci[1]:.3f}" if ci else "—"
            lines.append(f"| {v['label']} | {v['auc']:.3f} | {ci_text} | {v['leakage']} |")
        delta = o["leakage_delta"]
        if delta.get("available"):
            lines += [
                "",
                f"Leakage delta: total **{delta['total_auc']:.3f}** − structural **{delta['structural_auc']:.3f}** "
                f"= **{delta['delta']:+.3f}** AUC. {delta['interpretation']}",
            ]
        sel = o["selection_effect"]
        if sel.get("available"):
            lines += [
                "",
                f"Selection effect: structural AUC is **{sel['contacted_only_auc']:.3f}** on the "
                f"{sel['contacted_only_n']} contacted accounts and **{sel['all_accounts_auc']:.3f}** across all "
                f"{sel['all_accounts_n']}. {sel['note']}",
            ]
        structural = o["variants"]["structural"]
        lines += ["", "### Working the list top-down (structural score)", ""]
        lines += _bucket_table(structural["buckets"], "Bin")
        lines += ["", "| Top K | Converted | Precision | Expected at random | Lift | Recall |"]
        lines += ["| ---: | ---: | ---: | ---: | ---: | ---: |"]
        for p in structural["precision_at_k"]:
            lines.append(
                f"| {p['k']} | {p['hits']} | {_pct(p['precision'])} | {p['random_expected']} | "
                f"{p['lift']:.2f}× | {_pct(p['recall'])} |"
            )
        if structural["warnings"]:
            lines += ["", "**Warnings**", ""] + [f"- {w}" for w in structural["warnings"]]

    lines += ["", "## Caveats", ""] + [f"- {c}" for c in report["caveats"]]
    lines += ["", "⚠︎ marks a bucket below the small-sample floor; read its interval, not its rate.", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Backtest the ICP score against realised outcomes.")
    parser.add_argument("--json", action="store_true", help="emit the raw report instead of markdown")
    parser.add_argument("--out", type=Path, help="write to this file instead of stdout")
    args = parser.parse_args(argv)

    with session_scope() as db:
        ws = db.scalars(select(Workspace).order_by(Workspace.created_at)).first()
        if ws is None:
            print("No workspace found. Run `make seed` first.", file=sys.stderr)
            return 1
        report = scoring_eval.run(db, ws.id)

    text = json.dumps(report, indent=2, default=str) if args.json else render(report)
    if args.out:
        args.out.write_text(text + "\n")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
