import { Badge } from "@/components/ui/badge";

/** Seeded, illustrative history. Distinguishes it from runs/events the engine actually executed. */
export function HistoryBadge() {
  return (
    <Badge tone="warning" title="Seeded illustrative history: this record was generated by the demo seed, not executed by the engine">
      HISTORY (synthetic)
    </Badge>
  );
}

/** Marks records the engine really executed in this environment. */
export function ExecutedBadge() {
  return (
    <Badge tone="accent" title="Executed by the GTMOS workflow engine in this environment">
      EXECUTED
    </Badge>
  );
}
