import { ActionButton } from "@/components/ui/action-button";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { Panel } from "@/components/ui/panel";
import { EmptyState } from "@/components/ui/states";
import { pct, relTime, titleCase } from "@/lib/format";
import type { Claim, ResearchReport } from "@/lib/types";

const SECTIONS = [
  "account_summary",
  "why_now",
  "relevant_signals",
  "likely_pain",
  "technical_context",
  "buying_committee",
  "potential_objections",
  "recommended_angle",
];

function Refs({ refs }: { refs: string[] }) {
  return (
    <span className="ml-1 inline-flex gap-0.5 align-baseline">
      {refs.map((r) => (
        <a
          key={r}
          href={`#ev-${r}`}
          className="rounded bg-accent-soft px-1 font-mono text-[10px] text-accent-text hover:underline"
          aria-label={`Evidence ${r}`}
        >
          {r}
        </a>
      ))}
    </span>
  );
}

function ClaimLine({ c }: { c: Claim }) {
  return (
    <li className="text-sm leading-relaxed">
      {c.hypothesis && (
        <Badge tone="info" className="mr-1.5" title="An inference motivated by the cited evidence, not a verified fact">
          Hypothesis
        </Badge>
      )}
      {c.text}
      <Refs refs={c.evidence} />
    </li>
  );
}

export function ResearchPanel({ accountId, report }: { accountId: string; report: ResearchReport | null }) {
  const generate = (
    <ActionButton path={`/accounts/${accountId}/research`} body={{ use_llm: true }} variant="primary">
      {report ? "Regenerate research" : "Generate research"}
    </ActionButton>
  );
  if (!report) {
    return (
      <Panel title="Account research">
        <EmptyState
          title="No research yet"
          description="Research is built from an evidence pack of records GTMOS holds (signals, firmographics, contacts, activity). Every claim must cite evidence."
          action={generate}
        />
      </Panel>
    );
  }
  const meta = report.sections._meta ?? {};
  return (
    <div className="grid gap-4 xl:grid-cols-[1fr_360px]">
      <Panel
        title="Account research"
        description={
          <span>
            {report.generator === "demo-deterministic" ? "Deterministic demo generator (restates evidence only)" : `Generated by ${report.generator}`}
            {" · "}
            {relTime(report.created_at)} · {report.prompt_version}
          </span>
        }
        actions={
          <>
            <StatusBadge status={report.status === "draft" ? "draft" : report.status === "reviewed" ? "approved" : "rejected"} label={report.status} />
            {generate}
          </>
        }
      >
        <div className="mb-4 rounded-md border border-border bg-panel-2 px-3 py-2 text-xs text-muted">
          AI research is a <strong className="text-text">draft</strong>. It never becomes CRM truth automatically. Claims without valid
          citations are removed before display{report.unsupported_claims.length ? ` (${report.unsupported_claims.length} removed)` : ""}.
          {meta.llm_fallback_reason && <> Live LLM unavailable ({meta.llm_fallback_reason}); used the deterministic generator.</>}
        </div>
        <div className="space-y-5">
          {SECTIONS.map((key) => {
            const claims = (report.sections[key] as Claim[] | undefined) ?? [];
            if (!claims.length) return null;
            return (
              <section key={key}>
                <h3 className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted">{titleCase(key)}</h3>
                <ul className="space-y-1.5">
                  {claims.map((c, i) => (
                    <ClaimLine key={i} c={c} />
                  ))}
                </ul>
              </section>
            );
          })}
        </div>
        <div className="mt-5 flex flex-wrap gap-2 border-t border-border pt-4">
          <ActionButton path={`/research/${report.id}/review`} body={{ status: "reviewed" }} disabled={report.status === "reviewed"}>
            Mark reviewed
          </ActionButton>
          <ActionButton path={`/research/${report.id}/review`} body={{ status: "rejected" }} variant="ghost" disabled={report.status === "rejected"}>
            Reject
          </ActionButton>
        </div>
      </Panel>
      <Panel title={`Evidence (${report.evidence.length})`} description="Numbered records every claim must cite" bodyClassName="p-0">
        <ol className="divide-y divide-border">
          {report.evidence.map((e) => (
            <li key={e.id} id={`ev-${e.ref}`} className="scroll-mt-24 px-4 py-2.5 target:bg-accent-soft">
              <div className="flex items-center gap-2 text-xs">
                <span className="font-mono text-[10px] text-accent-text">{e.ref}</span>
                <Badge>{e.kind}</Badge>
                <span className="ml-auto text-[11px] text-muted">{pct(e.confidence, 0)}</span>
              </div>
              <div className="mt-1 text-xs font-medium">{e.label}</div>
              <div className="mt-0.5 text-[11px] text-muted">{e.detail}</div>
              <div className="mt-0.5 text-[10px] text-subtle">
                {e.source}
                {e.observed_at ? ` · ${relTime(e.observed_at)}` : ""}
              </div>
            </li>
          ))}
        </ol>
        {report.unsupported_claims.length > 0 && (
          <div className="border-t border-border px-4 py-3">
            <div className="text-xs font-medium text-danger">Removed claims (no valid citation)</div>
            <ul className="mt-1 space-y-1 text-[11px] text-muted">
              {report.unsupported_claims.map((u, i) => (
                <li key={i}>
                  <s>{u.text}</s> ({u.reason})
                </li>
              ))}
            </ul>
          </div>
        )}
      </Panel>
    </div>
  );
}
