import { ShieldCheck } from "lucide-react";

import { PageHeader } from "@/components/ui/page-header";
import { api, settle } from "@/lib/api";

import { CopilotChat } from "./copilot-chat";

export const metadata = { title: "GTM Copilot" };

export default async function CopilotPage() {
  const [suggestions] = await settle(api<string[]>("/copilot/suggestions"));

  return (
    <div className="space-y-4">
      <PageHeader
        title="GTM Copilot"
        description="Ask why pipeline moved, which segment converts, where accounts stall or whether an experiment worked. Answers come from the same analytics the dashboards use."
      />

      <div className="flex items-start gap-3 rounded-lg border border-accent/30 bg-accent-soft px-4 py-3">
        <ShieldCheck className="mt-0.5 size-4 shrink-0 text-accent-text" aria-hidden />
        <div className="text-xs">
          <p className="font-medium text-accent-text">The Copilot never writes SQL.</p>
          <p className="mt-0.5 text-muted">
            It classifies your question, routes it to a whitelist of approved, deterministic metric functions, and renders the answer
            from their computed values. Numbers are never generated by a model, and every answer shows the exact metric calls behind it.
          </p>
        </div>
      </div>

      <CopilotChat suggestions={suggestions ?? []} suggestionsFailed={suggestions === null} />
    </div>
  );
}
