"""Associations on simulated CRM objects

The demo adapter now mirrors HubSpot's association model so contact→company and deal→company
links are visible in the simulated CRM rather than only in the live adapter's code path.

Revision ID: a2fdf4cbee70
Revises: 360bc652007d
Create Date: 2026-09-22 20:29:07.654823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2fdf4cbee70'
down_revision: Union[str, Sequence[str], None] = '360bc652007d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_crm_objects', sa.Column('associations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_crm_objects', 'associations')
    # ### end Alembic commands ###
