"""Routing: SLAs, named accounts and an explicit fallback queue

The two boolean columns carry a server default so the migration can run against a populated table;
existing rows are neither named accounts nor the fallback rule.

Revision ID: 7d87d37fdf52
Revises: 8389f4163834
Create Date: 2026-09-22 16:03:12.485644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d87d37fdf52'
down_revision: Union[str, Sequence[str], None] = '8389f4163834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_named_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('routing_decisions', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('routing_rules', sa.Column('sla_hours', sa.Integer(), nullable=True))
    op.add_column('routing_rules', sa.Column('is_fallback', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routing_rules', 'is_fallback')
    op.drop_column('routing_rules', 'sla_hours')
    op.drop_column('routing_decisions', 'sla_due_at')
    op.drop_column('accounts', 'is_named_account')
    # ### end Alembic commands ###
