"""Runtime kill switches on the workspace

Environment variables gate what the system can do; these gate what it is doing right now, so an
operator can stop automation, outbound or CRM writes in seconds without a deploy. Existing
workspaces default to enabled, which is their current behaviour.

Revision ID: 360bc652007d
Revises: f6bd4247eb1c
Create Date: 2026-09-22 16:37:01.064507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360bc652007d'
down_revision: Union[str, Sequence[str], None] = 'f6bd4247eb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('automation_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('workspaces', sa.Column('outbound_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('workspaces', sa.Column('crm_writes_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('workspaces', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspaces', sa.Column('paused_by', sa.String(length=200), nullable=True))
    op.add_column('workspaces', sa.Column('paused_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'paused_reason')
    op.drop_column('workspaces', 'paused_by')
    op.drop_column('workspaces', 'paused_at')
    op.drop_column('workspaces', 'crm_writes_enabled')
    op.drop_column('workspaces', 'outbound_enabled')
    op.drop_column('workspaces', 'automation_enabled')
    # ### end Alembic commands ###
