"""Per-job detail counters on integration_syncs

The generic records_* columns cannot express job-specific numbers such as associations created or
accounts skipped for want of a company record.

Revision ID: 96c92b8fc3cd
Revises: a2fdf4cbee70
Create Date: 2026-09-22 20:32:02.342941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c92b8fc3cd'
down_revision: Union[str, Sequence[str], None] = 'a2fdf4cbee70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_syncs', sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_syncs', 'details')
    # ### end Alembic commands ###
