"""Record losing provider answers on field_provenance

Enrichment keeps the answer it chose; this column keeps the ones it rejected, so a contested
field can be shown as contested rather than as settled fact.

Revision ID: 8389f4163834
Revises: dc7baf1e87ed
Create Date: 2026-09-22 15:31:19.404880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8389f4163834'
down_revision: Union[str, Sequence[str], None] = 'dc7baf1e87ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_provenance', sa.Column('conflict', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_provenance', 'conflict')
    # ### end Alembic commands ###
