"""Store the disqualifying-signal penalty on icp_scores

Penalties apply after the category caps, so the five category columns no longer sum to the total
when an account carries one. Existing rows default to zero.

Revision ID: f6bd4247eb1c
Revises: 7d87d37fdf52
Create Date: 2026-09-22 16:16:32.508773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bd4247eb1c'
down_revision: Union[str, Sequence[str], None] = '7d87d37fdf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_scores', sa.Column('penalty', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icp_scores', 'penalty')
    # ### end Alembic commands ###
