"""GTM Stack Inspector: a health report on the go-to-market system itself.

Each section computes its status from live queries and cites the numbers it used. Recommendations are
generated by rules over those numbers, ranked by the number of high-value accounts they affect, and each
carries its evidence. If a number isn't in `evidence`, it isn't in the report.
"""

from __future__ import annotations

import uuid
from datetime import timedelta
from typing import Any

from sqlalchemy import and_, func, select
from sqlalchemy.orm import Session

from gtmos.models import (
    Account,
    Activity,
    Contact,
    DataQualityIssue,
    Engagement,
    Opportunity,
    RoutingDecision,
    Signal,
)
from gtmos.services import analytics, operations
from gtmos.services.attribution_service import run as run_attribution
from gtmos.services.common import utcnow

STATUS_ORDER = {"healthy": 0, "warning": 1, "critical": 2}


def _status(value: float, warn: float, crit: float, higher_is_worse: bool = True) -> str:
    if higher_is_worse:
        return "critical" if value >= crit else ("warning" if value >= warn else "healthy")
    return "critical" if value <= crit else ("warning" if value <= warn else "healthy")


def _live(ws: uuid.UUID) -> Any:
    return and_(Account.workspace_id == ws, Account.merged_into_id.is_(None))


def inspect(db: Session, ws: uuid.UUID) -> dict[str, Any]:
    now = utcnow()
    sections: list[dict[str, Any]] = []
    recs: list[dict[str, Any]] = []
    total_accounts = db.scalar(select(func.count()).select_from(Account).where(_live(ws))) or 1
    dq_open = dict(
        db.execute(
            select(DataQualityIssue.rule_key, func.count())
            .where(DataQualityIssue.workspace_id == ws, DataQualityIssue.status == "open")
            .group_by(DataQualityIssue.rule_key)
        )
        .tuples()
        .all()
    )

    # CRM ---------------------------------------------------------------------------------------------
    sync = operations.sync_health(db, ws, days=7)
    hrs = sync["hours_since_success"]
    crm_status = "critical" if hrs is None or hrs > 48 else _status(sync["record_failure_rate"], 0.02, 0.1)
    sections.append(
        {
            "key": "crm",
            "title": "CRM sync",
            "status": crm_status,
            "headline": (
                "No successful sync on record"
                if hrs is None
                else f"Last successful sync {hrs:.0f}h ago · {sync['record_failure_rate']:.1%} record failures (7d)"
            ),
            "simulated": sync["all_simulated"],
            "evidence": {
                "runs_7d": sync["runs"],
                "failed_runs_7d": sync["failed_runs"],
                "partial_runs_7d": sync["partial_runs"],
                "records_changed_7d": sync["records_changed"],
                "records_failed_7d": sync["records_failed"],
                "retries_7d": sync["retries"],
                "bad_external_ids": dq_open.get("bad_external_id", 0),
                "duplicate_accounts": dq_open.get("duplicate_account", 0),
            },
        }
    )

    # Enrichment --------------------------------------------------------------------------------------
    fields = {
        "domain": Account.domain,
        "industry": Account.industry,
        "employee_count": Account.employee_count,
        "region": Account.region,
        "ai_team_size": Account.ai_team_size,
    }
    field_cov = {
        k: round(
            (db.scalar(select(func.count()).select_from(Account).where(_live(ws), col.is_not(None))) or 0)
            / total_accounts,
            4,
        )
        for k, col in fields.items()
    }
    complete = (
        db.scalar(
            select(func.count()).select_from(Account).where(_live(ws), *[c.is_not(None) for c in fields.values()])
        )
        or 0
    )
    coverage = complete / total_accounts
    providers = operations.provider_health(db, ws)
    stale = dq_open.get("stale_enrichment", 0)
    sections.append(
        {
            "key": "enrichment",
            "title": "Enrichment",
            "status": _status(coverage, 0.9, 0.75, higher_is_worse=False),
            "headline": f"{coverage:.0%} of accounts fully enriched · {1 - coverage:.0%} incomplete · {stale} stale",
            "simulated": all(p["provider"].startswith("demo_") for p in providers),
            "evidence": {
                "accounts": total_accounts,
                "fully_enriched": complete,
                "field_coverage": field_cov,
                "stale_accounts": stale,
                "providers": [
                    {
                        "provider": p["provider"],
                        "hit_rate": p["hit_rate"],
                        "error_rate": p["error_rate"],
                        "cost_credits_30d": p["cost_credits"],
                    }
                    for p in providers
                ],
            },
        }
    )
    missing_core = total_accounts - complete
    if missing_core:
        recs.append(
            {
                "key": "enrichment_waterfall",
                "title": "Schedule the enrichment waterfall for incomplete accounts",
                "impact_accounts": missing_core,
                "priority_accounts": dq_open.get("missing_employee_count", 0),
                "why": f"{missing_core} accounts lack at least one core field "
                f"({', '.join(k for k, v in field_cov.items() if v < 1)}); "
                f"{stale} scored accounts have enrichment older than 180 days.",
                "how": "Nightly workflow: accounts with missing core fields or stale enrichment → enrich_account → "
                "recalculate_score. The waterfall already falls back across providers.",
                "evidence": {"missing_core_fields": missing_core, "stale": stale},
            }
        )

    # Routing -----------------------------------------------------------------------------------------
    since90 = now - timedelta(days=90)
    unmatched = (
        db.execute(
            select(Account.region, func.count(func.distinct(RoutingDecision.account_id)))
            .join(Account, Account.id == RoutingDecision.account_id)
            .where(
                RoutingDecision.workspace_id == ws,
                RoutingDecision.outcome == "unmatched",
                RoutingDecision.decided_at >= since90,
            )
            .group_by(Account.region)
        )
        .tuples()
        .all()
    )
    unmatched_by_region = {r or "unknown": n for r, n in unmatched}
    conflicts = (
        db.scalar(
            select(func.count())
            .select_from(RoutingDecision)
            .where(
                RoutingDecision.workspace_id == ws,
                RoutingDecision.decided_at >= since90,
                func.jsonb_array_length(RoutingDecision.conflicts) > 0,
            )
        )
        or 0
    )
    unowned_ab = (
        db.scalar(
            select(func.count())
            .select_from(Account)
            .where(
                _live(ws),
                Account.owner_id.is_(None),
                Account.score_grade.in_(["A", "B"]),
                Account.is_customer.is_(False),
            )
        )
        or 0
    )
    load = analytics.owner_load(db, ws)
    over = [u for u in load if u["is_active"] and u["capacity"] and u["open_accounts"] > u["capacity"]]
    inactive_owned = [u for u in load if not u["is_active"] and u["open_accounts"] > 0]
    lat = operations.routing_latency(db, ws)
    r_status = "critical" if unowned_ab >= 10 else ("warning" if unowned_ab or inactive_owned or over else "healthy")
    sections.append(
        {
            "key": "routing",
            "title": "Routing",
            "status": r_status,
            "headline": (
                f"{unowned_ab} A/B accounts unowned · {sum(unmatched_by_region.values())} unmatched decisions "
                f"(90d) · {conflicts} rule conflicts resolved"
            ),
            "evidence": {
                "unmatched_by_region_90d": unmatched_by_region,
                "conflicts_90d": conflicts,
                "unowned_ab_accounts": unowned_ab,
                "over_capacity_owners": [u["name"] for u in over],
                "inactive_owners_with_accounts": {u["name"]: u["open_accounts"] for u in inactive_owned},
                "median_signal_to_owner_hours": lat["median_signal_to_owner_hours"],
            },
        }
    )
    if unmatched_by_region:
        gap = max(unmatched_by_region.items(), key=lambda kv: kv[1])
        recs.append(
            {
                "key": "territory_gap",
                "title": f"Add a routing rule for {gap[0]}",
                "impact_accounts": sum(unmatched_by_region.values()),
                "priority_accounts": unowned_ab,
                "why": f"{sum(unmatched_by_region.values())} accounts matched no rule in 90 days "
                f"({', '.join(f'{k}: {v}' for k, v in unmatched_by_region.items())}). They land in triage "
                "and stall after replying.",
                "how": f"Add a '{gap[0]} → pool' rule (or a catch-all) so every region has an owner path.",
                "evidence": {"unmatched_by_region": unmatched_by_region, "unowned_ab": unowned_ab},
            }
        )
    if inactive_owned:
        n = sum(u["open_accounts"] for u in inactive_owned)
        recs.append(
            {
                "key": "reassign_departed",
                "title": "Reassign accounts owned by inactive reps",
                "impact_accounts": n,
                "priority_accounts": n,
                "why": f"{n} open accounts are owned by deactivated users "
                f"({', '.join(u['name'] for u in inactive_owned)}).",
                "how": "Re-run routing for those accounts; the engine reassigns when the owner is inactive.",
                "evidence": {"inactive_owners": {u["name"]: u["open_accounts"] for u in inactive_owned}},
            }
        )

    # Data quality ------------------------------------------------------------------------------------
    sev = dict(
        db.execute(
            select(DataQualityIssue.severity, func.count())
            .where(DataQualityIssue.workspace_id == ws, DataQualityIssue.status == "open")
            .group_by(DataQualityIssue.severity)
        )
        .tuples()
        .all()
    )
    sections.append(
        {
            "key": "data_quality",
            "title": "Data quality",
            "status": "critical" if sev.get("high", 0) > 25 else ("warning" if sum(sev.values()) else "healthy"),
            "headline": (
                f"{dq_open.get('duplicate_contact', 0)} duplicate contacts · "
                f"{dq_open.get('missing_employee_count', 0)} accounts missing employee count · "
                f"{sum(dq_open.values())} open issues"
            ),
            "evidence": {"open_by_rule": dq_open, "open_by_severity": sev},
        }
    )
    dupes = dq_open.get("duplicate_contact", 0) + dq_open.get("duplicate_account", 0)
    if dupes:
        recs.append(
            {
                "key": "crm_dedupe",
                "title": "Automate CRM deduplication before sync",
                "impact_accounts": dupes,
                "priority_accounts": dq_open.get("duplicate_account", 0),
                "why": f"{dq_open.get('duplicate_contact', 0)} duplicate contact groups and "
                f"{dq_open.get('duplicate_account', 0)} duplicate account groups split activity history.",
                "how": "Run the dedupe rules on ingest (normalized email/domain) and merge with audit before the "
                "reverse-ETL job; upserting on unique keys prevents new CRM duplicates.",
                "evidence": {
                    "duplicate_contacts": dq_open.get("duplicate_contact", 0),
                    "duplicate_accounts": dq_open.get("duplicate_account", 0),
                },
            }
        )
    lc = dq_open.get("lifecycle_conflict", 0) + dq_open.get("invalid_pipeline_transition", 0)
    if lc:
        recs.append(
            {
                "key": "lifecycle_cleanup",
                "title": "Clean up lifecycle and stage history",
                "impact_accounts": lc,
                "priority_accounts": 0,
                "why": f"{dq_open.get('lifecycle_conflict', 0)} lifecycle conflicts and "
                f"{dq_open.get('invalid_pipeline_transition', 0)} invalid stage transitions distort funnel metrics.",
                "how": "Enforce forward-only lifecycle in the CRM sync mapping and backfill the missing stages.",
                "evidence": {
                    "lifecycle_conflicts": dq_open.get("lifecycle_conflict", 0),
                    "invalid_transitions": dq_open.get("invalid_pipeline_transition", 0),
                },
            }
        )

    # Product signal sync ------------------------------------------------------------------------------
    wh = operations.webhook_health(db, ws, days=7)
    ph_last = wh["last_received"].get("posthog")
    eng_total = db.scalar(select(func.count()).select_from(Engagement).where(Engagement.workspace_id == ws)) or 0
    eng_unmatched = (
        db.scalar(
            select(func.count())
            .select_from(Engagement)
            .where(Engagement.workspace_id == ws, Engagement.account_id.is_(None))
        )
        or 0
    )
    stale_hours = (now - ph_last).total_seconds() / 3600 if ph_last else None
    sections.append(
        {
            "key": "product_signals",
            "title": "Product signal sync",
            "status": "critical" if stale_hours is None or stale_hours > 24 else _status(wh["failure_rate"], 0.02, 0.1),
            "headline": (
                f"Last product event {stale_hours:.0f}h ago · {wh['failure_rate']:.1%} webhook failures (7d) · "
                f"{eng_unmatched} unmatched events"
                if stale_hours is not None
                else "No product events received"
            ),
            "evidence": {
                "webhooks_7d": wh["total"],
                "failure_rate_7d": wh["failure_rate"],
                "duplicates_absorbed_7d": wh["duplicates_absorbed"],
                "engagement_events": eng_total,
                "unmatched_events": eng_unmatched,
            },
        }
    )
    pql = db.execute(
        select(Signal.account_id, Signal.observed_at).where(
            Signal.workspace_id == ws,
            Signal.signal_type == "usage_threshold",
            Signal.observed_at >= now - timedelta(days=60),
        )
    ).all()
    slow = 0
    for acc, at in pql:
        touched = (
            db.scalar(
                select(func.count())
                .select_from(Activity)
                .where(
                    Activity.account_id == acc,
                    Activity.occurred_at >= at,
                    Activity.occurred_at <= at + timedelta(days=3),
                    Activity.type.in_(["email_sent", "task", "meeting_booked", "call"]),
                )
            )
            or 0
        )
        slow += 0 if touched else 1
    if slow:
        recs.append(
            {
                "key": "pql_routing",
                "title": "Route product-qualified accounts within one business day",
                "impact_accounts": slow,
                "priority_accounts": slow,
                "why": f"{slow} of {len(pql)} accounts that crossed the usage threshold in 60 days had no sales "
                "touch within 3 days.",
                "how": "Enable the 'Product-qualified account → AE' workflow (route + task + lifecycle) on the "
                "usage_threshold event.",
                "evidence": {"pql_accounts_60d": len(pql), "untouched_within_3d": slow},
            }
        )

    # Buying-signal coverage ---------------------------------------------------------------------------
    hot = db.execute(
        select(Signal.account_id, func.max(Signal.observed_at))
        .join(Account, Account.id == Signal.account_id)
        .where(
            Signal.workspace_id == ws,
            Signal.signal_type.in_(["funding_round", "ai_product_launch", "executive_hire", "ai_hiring_surge"]),
            Signal.observed_at >= now - timedelta(days=14),
            Account.score_grade.in_(["A", "B"]),
        )
        .group_by(Signal.account_id)
    ).all()
    untouched = 0
    for acc, at in hot:
        t = (
            db.scalar(
                select(func.count())
                .select_from(Activity)
                .where(
                    Activity.account_id == acc,
                    Activity.occurred_at >= at - timedelta(days=1),
                    Activity.type.in_(["email_sent", "task", "meeting_booked"]),
                )
            )
            or 0
        )
        untouched += 0 if t else 1
    if untouched:
        recs.append(
            {
                "key": "buying_signal_workflow",
                "title": "Act on fresh buying signals automatically",
                "impact_accounts": untouched,
                "priority_accounts": untouched,
                "why": f"{untouched} A/B accounts had a funding, launch, executive or hiring signal in the "
                "last 14 days with no outreach since.",
                "how": "The 'Funding signal → research → outreach draft' workflow drafts evidence-grounded outreach "
                "into the approval queue within minutes of the signal.",
                "evidence": {"ab_accounts_with_fresh_signals": len(hot), "no_touch_since_signal": untouched},
            }
        )

    # Attribution --------------------------------------------------------------------------------------
    attr = run_attribution(db, ws, days=180)
    unattr_share = (attr["unattributed_opportunities"] / attr["opportunities"]) if attr["opportunities"] else 0
    sections.append(
        {
            "key": "attribution",
            "title": "Attribution",
            "status": _status(unattr_share, 0.15, 0.35),
            "headline": f"Incomplete for {unattr_share:.0%} of opportunities (180d)",
            "evidence": {
                "opportunities_180d": attr["opportunities"],
                "unattributed_opportunities": attr["unattributed_opportunities"],
                "unattributed_pipeline": attr["unattributed_pipeline"],
            },
        }
    )

    # Workflows ----------------------------------------------------------------------------------------
    wf = operations.workflow_health(db, ws, days=30)
    sections.append(
        {
            "key": "workflows",
            "title": "Automation reliability",
            "status": _status(wf["failure_rate"], 0.03, 0.1),
            "headline": (
                f"{wf['failure_rate']:.1%} of executed runs failed (30d) · {wf['dead_letter_total']} in dead letter · "
                f"{wf['retried_steps']} steps recovered by retry"
            ),
            "evidence": {
                "by_status_30d": wf["by_status"],
                "dead_letter_total": wf["dead_letter_total"],
                "retried_steps_30d": wf["retried_steps"],
            },
        }
    )

    # Outbound hygiene ---------------------------------------------------------------------------------
    since30 = now - timedelta(days=30)
    sent = (
        db.scalar(
            select(func.count())
            .select_from(Activity)
            .where(Activity.workspace_id == ws, Activity.type == "email_sent", Activity.occurred_at >= since30)
        )
        or 0
    )
    bounced = (
        db.scalar(
            select(func.count())
            .select_from(Activity)
            .where(Activity.workspace_id == ws, Activity.type == "email_bounced", Activity.occurred_at >= since30)
        )
        or 0
    )
    invalid_contacts = (
        db.scalar(
            select(func.count())
            .select_from(Contact)
            .where(
                Contact.workspace_id == ws,
                Contact.merged_into_id.is_(None),
                Contact.email_status == "invalid",
                Contact.do_not_contact.is_(False),
            )
        )
        or 0
    )
    bounce = bounced / sent if sent else 0.0
    sections.append(
        {
            "key": "outbound",
            "title": "Outbound hygiene",
            "status": _status(bounce, 0.02, 0.05),
            "headline": f"{bounce:.1%} bounce rate (30d) · {invalid_contacts} invalid emails not suppressed",
            "evidence": {
                "sent_30d": sent,
                "bounced_30d": bounced,
                "invalid_unsuppressed": invalid_contacts,
                "note": "Deliverability also depends on SPF/DKIM/DMARC and domain warm-up, which GTMOS "
                "does not manage.",
            },
        }
    )

    stuck = analytics.stuck_accounts(db, ws)
    open_opps_idle = (
        db.scalar(
            select(func.count())
            .select_from(Opportunity)
            .where(Opportunity.workspace_id == ws, Opportunity.stage.in_(analytics.OPEN_DEAL))
        )
        or 0
    )
    recs.sort(key=lambda r: (-r["priority_accounts"], -r["impact_accounts"]))
    for i, r in enumerate(recs, start=1):
        r["rank"] = i
    overall = max((s["status"] for s in sections), key=lambda s: STATUS_ORDER[s])
    return {
        "generated_at": now,
        "overall_status": overall,
        "summary": {
            "healthy": sum(s["status"] == "healthy" for s in sections),
            "warning": sum(s["status"] == "warning" for s in sections),
            "critical": sum(s["status"] == "critical" for s in sections),
        },
        "sections": sections,
        "recommendations": recs,
        "context": {
            "stuck_accounts": stuck["total"],
            "stuck_by_stage": stuck["by_stage"],
            "open_opportunities": open_opps_idle,
        },
        "method": "Every status and recommendation is computed from live queries at request time; "
        "thresholds are defined in services/stack_inspector.py.",
    }
