"""GTM Stack Inspector: a health report on the go-to-market system itself.

Each section computes its status from live queries and cites the numbers it used. Recommendations are
generated by rules over those numbers, ranked by the number of high-value accounts they affect, and each
carries its evidence. If a number isn't in `evidence`, it isn't in the report.

`causal_chains` goes one step further than a list of findings: it traces one set of accounts from a root
cause, through the mechanism that propagates it, to the business consequence, intersecting the same ids at
every link. Two findings that sound related ("36 accounts missing employee count", "90 unmatched routing
decisions") are usually not the same accounts, and the honest number is the intersection.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from typing import Any

from sqlalchemy import and_, func, select
from sqlalchemy.orm import Session

from gtmos.domain.icp import ICPDefinition
from gtmos.domain.scoring import grade_for
from gtmos.models import (
    Account,
    Activity,
    Contact,
    DataQualityIssue,
    Engagement,
    EnrichmentRun,
    FieldProvenance,
    ICPScore,
    Opportunity,
    RoutingDecision,
    RoutingRule,
    ScoreComponent,
    Signal,
)
from gtmos.seed.profiles import segment_for
from gtmos.services import analytics, operations
from gtmos.services.attribution_service import run as run_attribution
from gtmos.services.common import utcnow
from gtmos.services.scoring_service import active_icp

STATUS_ORDER = {"healthy": 0, "warning": 1, "critical": 2}
TOUCH_TYPES = ("email_sent", "task", "meeting_booked", "call")


def _status(value: float, warn: float, crit: float, higher_is_worse: bool = True) -> str:
    if higher_is_worse:
        return "critical" if value >= crit else ("warning" if value >= warn else "healthy")
    return "critical" if value <= crit else ("warning" if value <= warn else "healthy")


def _live(ws: uuid.UUID) -> Any:
    return and_(Account.workspace_id == ws, Account.merged_into_id.is_(None))


# Causal chains ---------------------------------------------------------------------------------------

# Outcomes that mean "no territory rule claimed this account". `fallback_queue` is the routine one now
# that a triage queue exists; `unmatched` survives for workspaces with no queue configured, and for
# decisions recorded before the queue was introduced. Counting only one of them would make the chains
# silently empty the moment the queue was added — which is exactly what happened once.
UNCLAIMED_OUTCOMES = ("unmatched", "fallback_queue")


def _ids(db: Session, stmt: Any) -> set[uuid.UUID]:
    return {i for i in db.scalars(stmt) if i is not None}


class _Chain:
    """One causal chain under construction.

    Every step *intersects* the running set of account ids, so a link can never count an account the
    previous link did not contain. That constraint is the point of the class: "36 accounts missing
    employee count" and "90 unmatched routing decisions" are two true numbers about largely different
    accounts, and quoting them side by side implies a chain that the intersection does not support.
    """

    def __init__(
        self,
        key: str,
        title: str,
        label: str,
        root: set[uuid.UUID],
        sentence: str,
        query: str,
        **evidence: Any,
    ) -> None:
        self.key = key
        self.title = title
        self.ids = set(root)
        self.links: list[dict[str, Any]] = []
        self._append(label, sentence, query, evidence)

    def _append(self, label: str, sentence: str, query: str, evidence: dict[str, Any]) -> None:
        self.links.append(
            {
                "step": len(self.links) + 1,
                "label": label,
                "count": len(self.ids),
                "sentence": sentence.format(n=len(self.ids)),
                "query": query,
                "evidence": evidence,
            }
        )

    def step(self, label: str, keep: set[uuid.UUID], sentence: str, query: str, **evidence: Any) -> None:
        self.ids &= keep
        self._append(label, sentence, query, evidence)

    def build(
        self,
        db: Session,
        *,
        consequence: dict[str, Any],
        fix: dict[str, Any],
        confidence: dict[str, Any],
    ) -> dict[str, Any] | None:
        # No account survives every link, so the chain is a story the data does not tell. Showing it
        # with zeros would read as "this happens, rarely"; it is better to show nothing.
        if not self.ids:
            return None
        return {
            "key": self.key,
            "title": self.title,
            "root_cause": self.links[0]["label"],
            "consequence_label": consequence["label"],
            "links": self.links,
            "consequence": consequence,
            "fix": fix,
            "confidence": confidence,
            "accounts": _sample(db, self.ids),
            "traced_accounts": len(self.ids),
        }


def _sample(db: Session, ids: set[uuid.UUID], limit: int = 6) -> list[dict[str, Any]]:
    """A few of the accounts that survived every link, so the chain can be checked by hand."""
    rows = db.execute(
        select(Account.id, Account.name, Account.icp_score, Account.score_grade, Account.region)
        .where(Account.id.in_(list(ids)))
        .order_by(Account.icp_score.desc().nullslast(), Account.name)
        .limit(limit)
    ).all()
    return [
        {"id": str(r.id), "name": r.name, "icp_score": r.icp_score, "grade": r.score_grade, "region": r.region}
        for r in rows
    ]


def _open_pipeline(db: Session, ws: uuid.UUID, ids: set[uuid.UUID]) -> float:
    total = db.scalar(
        select(func.coalesce(func.sum(Opportunity.amount_usd), 0.0)).where(
            Opportunity.workspace_id == ws,
            Opportunity.stage.in_(analytics.OPEN_DEAL),
            Opportunity.account_id.in_(list(ids)),
        )
    )
    return float(total or 0.0)


def _icp_sum(db: Session, ids: set[uuid.UUID]) -> int:
    total = db.scalar(select(func.coalesce(func.sum(Account.icp_score), 0)).where(Account.id.in_(list(ids))))
    return int(total or 0)


def _tier(icp: ICPDefinition, industry: Any) -> str:
    if industry in icp.core_industries:
        return "core"
    if industry in icp.adjacent_industries:
        return "adjacent"
    return "outside"


def _material_conflicts(db: Session, ws: uuid.UUID, field: str) -> list[tuple[uuid.UUID, dict[str, Any]]]:
    """Account-level provenance rows where a second provider confidently contradicted the kept value.

    The waterfall has already discarded cosmetic differences, so everything here is a real fork in the
    data: two sources, one of them wrong, nothing in the record saying which.
    """
    rows = db.execute(
        select(FieldProvenance.entity_id, FieldProvenance.conflict)
        .join(Account, Account.id == FieldProvenance.entity_id)
        .where(
            FieldProvenance.workspace_id == ws,
            FieldProvenance.entity_type == "account",
            FieldProvenance.field == field,
            FieldProvenance.conflict.is_not(None),
            Account.merged_into_id.is_(None),
        )
    ).all()
    return [(r.entity_id, r.conflict) for r in rows if (r.conflict or {}).get("material")]


def _rule_regions(rules: list[RoutingRule]) -> set[str]:
    covered: set[str] = set()
    for rule in rules:
        for cond in rule.conditions:
            if isinstance(cond, dict) and cond.get("field") == "account.region":
                value = cond.get("value")
                values = value if isinstance(value, list) else [value]
                covered.update(v for v in values if isinstance(v, str))
    return covered


def causal_chains(db: Session, ws: uuid.UUID, now: datetime) -> list[dict[str, Any]]:
    """Root cause → mechanism → consequence, with one account set traced through every link."""
    since90 = now - timedelta(days=90)
    rules = list(db.scalars(select(RoutingRule).where(RoutingRule.workspace_id == ws, RoutingRule.is_active.is_(True))))
    segment_rules = {
        r.id for r in rules if any(isinstance(c, dict) and c.get("field") == "account.segment" for c in r.conditions)
    }
    covered_regions = _rule_regions(rules)

    no_size = _ids(db, select(Account.id).where(_live(ws), Account.employee_count.is_(None)))
    no_segment = _ids(db, select(Account.id).where(_live(ws), Account.segment.is_(None)))
    no_domain = _ids(db, select(Account.id).where(_live(ws), Account.domain.is_(None)))
    unowned = _ids(db, select(Account.id).where(_live(ws), Account.owner_id.is_(None)))
    # An account the rules did not claim now lands in the triage queue rather than nowhere, so the end
    # of these chains is "generic queue instead of a territory owner", not "no owner at all". Both
    # states are the same failure — the rule set did not cover this account — and the fallback queue's
    # SLA is the loosest one configured, so the consequence is slower follow-up rather than none.
    in_fallback = _ids(
        db,
        select(RoutingDecision.account_id)
        .distinct()
        .where(
            RoutingDecision.workspace_id == ws,
            RoutingDecision.outcome == "fallback_queue",
            RoutingDecision.decided_at >= since90,
        ),
    )
    no_territory_owner = unowned | in_fallback
    graded_ab = _ids(db, select(Account.id).where(_live(ws), Account.score_grade.in_(["A", "B"])))
    unmatched_90d = _ids(
        db,
        select(RoutingDecision.account_id)
        .distinct()
        .where(
            RoutingDecision.workspace_id == ws,
            RoutingDecision.outcome.in_(UNCLAIMED_OUTCOMES),
            RoutingDecision.decided_at >= since90,
        ),
    )
    touched_30d = _ids(
        db,
        select(Activity.account_id)
        .distinct()
        .where(
            Activity.workspace_id == ws,
            Activity.type.in_(TOUCH_TYPES),
            Activity.occurred_at >= now - timedelta(days=30),
        ),
    )
    emailed_ever = _ids(
        db, select(Activity.account_id).distinct().where(Activity.workspace_id == ws, Activity.type == "email_sent")
    )

    built = [
        _chain_size_gap(
            db, ws, no_size, no_segment, unmatched_90d, no_territory_owner, touched_30d, rules, segment_rules
        ),
        _chain_domain_gap(db, ws, no_domain, graded_ab, emailed_ever),
        _chain_provider_conflict(db, ws, segment_rules),
        _chain_territory_gap(db, ws, covered_regions, no_segment, unmatched_90d, no_territory_owner, graded_ab, now),
    ]
    return [c for c in built if c is not None]


def _chain_size_gap(
    db: Session,
    ws: uuid.UUID,
    no_size: set[uuid.UUID],
    no_segment: set[uuid.UUID],
    unmatched_90d: set[uuid.UUID],
    unowned: set[uuid.UUID],
    touched_30d: set[uuid.UUID],
    rules: list[RoutingRule],
    segment_rules: set[uuid.UUID],
) -> dict[str, Any] | None:
    if not no_size:
        return None
    # The fork that proves the mechanism rather than asserting it: the only segment-less accounts the
    # router ever assigned were matched by the one active rule that does not test account.segment.
    matched_without_segment = db.execute(
        select(func.count(func.distinct(RoutingDecision.account_id)))
        .join(Account, Account.id == RoutingDecision.account_id)
        .where(
            RoutingDecision.workspace_id == ws,
            RoutingDecision.outcome != "unmatched",
            Account.segment.is_(None),
            Account.merged_into_id.is_(None),
        )
    ).scalar_one()
    zero_size_points = (
        db.scalar(
            select(func.count())
            .select_from(ScoreComponent)
            .join(ICPScore, ICPScore.id == ScoreComponent.icp_score_id)
            .where(
                ICPScore.is_current.is_(True),
                ICPScore.account_id.in_(list(no_size)),
                ScoreComponent.key == "company_size",
                ScoreComponent.points == 0,
            )
        )
        or 0
    )
    # What the same component is worth to an account that *does* have a count, and how many of the
    # unsized accounts would change grade if they earned it. A forecast, and labelled as one.
    median_size_points = float(
        db.scalar(
            select(func.percentile_cont(0.5).within_group(ScoreComponent.points))
            .select_from(ScoreComponent)
            .join(ICPScore, ICPScore.id == ScoreComponent.icp_score_id)
            .join(Account, Account.id == ICPScore.account_id)
            .where(
                _live(ws),
                ICPScore.is_current.is_(True),
                ScoreComponent.key == "company_size",
                Account.employee_count.is_not(None),
            )
        )
        or 0.0
    )
    totals = db.execute(
        select(ICPScore.total).where(
            ICPScore.workspace_id == ws, ICPScore.is_current.is_(True), ICPScore.account_id.in_(list(no_size))
        )
    ).scalars()
    grade_lift = sum(1 for t in totals if grade_for(int(t + median_size_points)) != grade_for(t))

    chain = _Chain(
        "size_gap_blocks_routing",
        "Missing employee count → no segment → no routing rule → no territory owner",
        "Employee count missing",
        no_size,
        "{n} live accounts have no employee count.",
        "accounts where employee_count is null and merged_into_id is null",
    )
    chain.step(
        "No segment",
        no_segment,
        "{n} of them also have no segment, because the segment band is derived from the employee count.",
        "… and segment is null",
        derivation="segment_for(employee_count): <100 smb, <500 mid_market, <2000 enterprise, else strategic",
    )
    chain.step(
        "No routing rule matches",
        unmatched_90d,
        "{n} of those reached the router in the last 90 days, and every one of them matched no rule.",
        "… and exists (routing_decisions where outcome = 'unmatched' and decided_at >= now() - 90 days)",
        segment_conditioned_rules=f"{len(segment_rules)} of {len(rules)} active rules test account.segment",
        segmentless_accounts_ever_matched=matched_without_segment,
        mechanism="The only rule that fires without a segment is the one that does not test it "
        "(existing customer → account management).",
    )
    chain.step(
        "No territory owner",
        unowned,
        "{n} ended up in the triage queue or with no owner at all, rather than with the rep whose "
        "territory they belong to.",
        "… and (owner_id is null or the last routing decision was 'fallback_queue')",
        why_it_matters="The triage queue carries the loosest first-touch SLA configured (72h) because "
        "it exists to catch what the rules missed, not to work a territory.",
    )
    untouched = chain.ids - touched_30d
    chain.step(
        "No follow-up",
        untouched,
        "{n} have had no email, call, task or meeting in the last 30 days.",
        "… and no activity of type email_sent/call/task/meeting_booked in 30 days",
    )
    return chain.build(
        db,
        consequence={
            "label": "Accounts with no territory owner",
            "accounts": len(chain.ids),
            "sentence": f"{len(chain.ids)} accounts reached the triage queue rather than a territory owner for a "
            "reason that started with one empty field, carrying "
            f"{_icp_sum(db, chain.ids)} points of ICP score and ${_open_pipeline(db, ws, chain.ids):,.0f} of open "
            "pipeline.",
            "metrics": {
                "icp_score_at_risk": _icp_sum(db, chain.ids),
                "open_pipeline_usd": _open_pipeline(db, ws, chain.ids),
                "accounts_scoring_zero_on_company_size": zero_size_points,
                "median_company_size_points_for_sized_peers": round(median_size_points, 1),
                "would_change_grade_if_enriched": grade_lift,
            },
        },
        fix={
            "title": "Backfill employee count, then re-segment and re-route in the same run",
            "how": "Nightly: accounts with a missing core field → enrich_account → recalculate_score → "
            "route_account. Routing has to run after segmentation or the account is unmatched again.",
            "expected_effect": f"{len(chain.ids)} accounts leave the triage queue; on the median peer's "
            f"company-size score, {grade_lift} of the {len(no_size)} unsized accounts change grade.",
            "rec_key": "enrichment_waterfall",
        },
        confidence={
            "level": "high",
            "basis": "mechanism",
            "statement": "Each link is a deterministic dependency, not a correlation: segment is computed "
            "from employee count, and the rules read segment. The counts are the intersection at every step.",
            "limits": f"This chain explains only {len(no_size & no_segment & unmatched_90d)} of the "
            f"{len(unmatched_90d)} accounts unmatched in 90 days; the rest have a segment and fail elsewhere. "
            "The grade-change figure is a forecast from peer scores, not an observation.",
        },
    )


def _chain_domain_gap(
    db: Session,
    ws: uuid.UUID,
    no_domain: set[uuid.UUID],
    graded_ab: set[uuid.UUID],
    emailed_ever: set[uuid.UUID],
) -> dict[str, Any] | None:
    if not no_domain:
        return None
    enriched_ok = _ids(
        db,
        select(EnrichmentRun.entity_id)
        .distinct()
        .where(
            EnrichmentRun.workspace_id == ws, EnrichmentRun.entity_type == "account", EnrichmentRun.status != "failed"
        ),
    )
    other_core_missing = _ids(
        db,
        select(Account.id).where(
            _live(ws),
            Account.domain.is_(None),
            (
                Account.industry.is_(None)
                | Account.employee_count.is_(None)
                | Account.region.is_(None)
                | Account.ai_team_size.is_(None)
            ),
        ),
    )
    avg_missing = db.scalar(
        select(func.avg(Account.icp_score)).where(_live(ws), Account.domain.is_(None), Account.icp_score.is_not(None))
    )
    avg_present = db.scalar(
        select(func.avg(Account.icp_score)).where(
            _live(ws), Account.domain.is_not(None), Account.icp_score.is_not(None)
        )
    )

    chain = _Chain(
        "domain_gap_blocks_enrichment",
        "Missing domain → enrichment cannot run → no firmographics → account never targeted",
        "Domain missing",
        no_domain,
        "{n} live accounts have no domain.",
        "accounts where domain is null and merged_into_id is null",
    )
    chain.step(
        "Enrichment cannot run",
        no_domain - enriched_ok,
        "{n} of them have never had an enrichment run finish: the waterfall is keyed on the domain and "
        "marks the run failed without one.",
        "… and no enrichment_runs row with status <> 'failed'",
        code="services/enrichment_service.py sets run.status = 'failed' when account.domain is empty",
        also_missing_another_core_field=len(other_core_missing & no_domain),
    )
    chain.step(
        "Never reaches A or B",
        set(chain.ids) - graded_ab,
        "{n} of those are graded C, D or not at all — no firmographics, no fit points.",
        "… and score_grade not in ('A','B')",
        avg_icp_score_without_domain=round(float(avg_missing or 0), 1),
        avg_icp_score_with_domain=round(float(avg_present or 0), 1),
    )
    chain.step(
        "Never contacted",
        set(chain.ids) - emailed_ever,
        "{n} have never been sent a single email.",
        "… and no activity of type email_sent, ever",
    )
    return chain.build(
        db,
        consequence={
            "label": "Accounts invisible to targeting",
            "accounts": len(chain.ids),
            "sentence": f"{len(chain.ids)} accounts cannot be enriched, cannot score, and have never been "
            "contacted. They are not rejected targets; they were never candidates.",
            "metrics": {
                "avg_icp_score_without_domain": round(float(avg_missing or 0), 1),
                "avg_icp_score_with_domain": round(float(avg_present or 0), 1),
                "accounts_never_emailed": len(chain.ids),
            },
        },
        fix={
            "title": "Resolve the domain first, from the contact emails already on the account",
            "how": "Before the enrichment waterfall, derive the domain from the most common non-free email "
            "domain among the account's contacts, then enrich; queue the rest for manual resolution.",
            "expected_effect": f"{len(no_domain)} accounts become enrichable; each one that scores at the "
            "average of its enriched peers gains the difference in the metrics below.",
            "rec_key": "enrichment_waterfall",
        },
        confidence={
            "level": "medium",
            "basis": "mechanism + correlation",
            "statement": "The block itself is mechanical and readable in the code: no domain, no waterfall. "
            "The score and outreach gaps are consistent with it.",
            "limits": f"Only {len(no_domain)} accounts are in the root set, far too few to treat the score "
            "difference as a rate. Nothing here shows these accounts would be good targets if enriched — "
            "only that the question has never been asked of them.",
        },
    )


def _chain_provider_conflict(db: Session, ws: uuid.UUID, segment_rules: set[uuid.UUID]) -> dict[str, Any] | None:
    size_conflicts = _material_conflicts(db, ws, "employee_count")
    industry_conflicts = _material_conflicts(db, ws, "industry")
    if not size_conflicts and not industry_conflicts:
        return None
    _, icp = active_icp(db, ws)

    def _others(conflict: dict[str, Any]) -> list[Any]:
        return [o.get("value") for o in (conflict.get("others") or [])]

    band_flip = {
        aid
        for aid, c in size_conflicts
        if any(segment_for(int(v)) != segment_for(int(c["chosen_value"])) for v in _others(c) if v is not None)
    }
    tier_flip = {
        aid
        for aid, c in industry_conflicts
        if any(_tier(icp, v) != _tier(icp, c.get("chosen_value")) for v in _others(c))
    }
    disputed = {aid for aid, _ in size_conflicts} | {aid for aid, _ in industry_conflicts}

    # A decision that already rests on the disputed value: an owner chosen by a segment-conditioned rule,
    # or a fit score that is currently claiming full credit for a core industry.
    routed_by_segment = _ids(
        db,
        select(RoutingDecision.account_id)
        .distinct()
        .where(RoutingDecision.workspace_id == ws, RoutingDecision.rule_id.in_(list(segment_rules))),
    )
    full_industry_credit = _ids(
        db,
        select(ICPScore.account_id)
        .join(ScoreComponent, ScoreComponent.icp_score_id == ICPScore.id)
        .where(
            ICPScore.workspace_id == ws,
            ICPScore.is_current.is_(True),
            ScoreComponent.key == "industry",
            ScoreComponent.points == ScoreComponent.max_points,
        ),
    )

    chain = _Chain(
        "provider_conflict_decides_owner",
        "Providers disagree → the derived segment or industry flips → the owner and the grade are a coin flip",
        "Sources contradict each other",
        disputed,
        "{n} accounts carry a material provider conflict on employee count or industry.",
        "field_provenance where conflict is not null and conflict->>'material' is true",
    )
    chain.step(
        "The derived value changes",
        band_flip | tier_flip,
        "For {n} of them the rejected answer lands in a different segment band or a different ICP "
        "industry tier — the disagreement is not cosmetic, it changes what the account *is*.",
        "segment_for(kept) <> segment_for(rejected), or ICP tier(kept) <> tier(rejected)",
        segment_band_flips=len(band_flip),
        industry_tier_flips=len(tier_flip),
        size_conflicts=len(size_conflicts),
        industry_conflicts=len(industry_conflicts),
    )
    chain.step(
        "A live decision rests on it",
        (band_flip & routed_by_segment) | (tier_flip & full_industry_credit),
        "{n} of those already have an owner chosen by a segment-conditioned rule, or a fit score taking "
        "full credit for a core industry the other source disputes.",
        "routing_decisions.rule_id in (rules testing account.segment), or score_components.industry at max points",
    )
    return chain.build(
        db,
        consequence={
            "label": "Owners and grades resting on a coin flip",
            "accounts": len(chain.ids),
            "sentence": f"{len(chain.ids)} accounts are routed or scored on a value that a second confident "
            "source contradicts. Nothing in the record says which source is right.",
            "metrics": {
                "segment_band_flips": len(band_flip),
                "industry_tier_flips": len(tier_flip),
                "decisions_resting_on_disputed_values": len(chain.ids),
            },
        },
        fix={
            "title": "Send material conflicts to a human decision with a manual lock",
            "how": "Re-run enrichment on the conflicting field; if the sources still disagree, queue the "
            "account for a one-click decision that writes a manual lock so the next run cannot flip it back.",
            "expected_effect": f"{len(chain.ids)} routing and scoring decisions stop depending on which "
            "provider answered last; the lock makes the choice auditable.",
            "rec_key": None,
        },
        confidence={
            "level": "high",
            "basis": "mechanism (exposure, not error)",
            "statement": "The band and tier arithmetic is deterministic, so 'the derived value would change' "
            "is a fact about the two values, not an estimate.",
            "limits": "This measures exposure, not mistakes. It does not claim the current owner or grade is "
            "wrong — only that the data does not settle it, and that a re-run could silently change it.",
        },
    )


def _chain_territory_gap(
    db: Session,
    ws: uuid.UUID,
    covered_regions: set[str],
    no_segment: set[uuid.UUID],
    unmatched_90d: set[uuid.UUID],
    unowned: set[uuid.UUID],
    graded_ab: set[uuid.UUID],
    now: datetime,
) -> dict[str, Any] | None:
    if not covered_regions:
        return None
    # Accounts that *do* have a segment, so the size chain cannot claim them: here the rule set itself is
    # the root cause, because no active rule names their region.
    uncovered = _ids(
        db,
        select(Account.id).where(
            _live(ws),
            Account.is_customer.is_(False),
            Account.segment.is_not(None),
            (Account.region.is_(None) | Account.region.not_in(list(covered_regions))),
        ),
    )
    uncovered -= no_segment
    if not uncovered:
        return None
    by_region = {
        region or "unknown": count
        for region, count in db.execute(
            select(Account.region, func.count())
            .where(Account.id.in_(list(uncovered & unmatched_90d)))
            .group_by(Account.region)
        )
        .tuples()
        .all()
    }
    unowned_rate = {
        (region or "unknown"): round(without_owner / total, 3)
        for region, total, without_owner in db.execute(
            select(Account.region, func.count(), func.count().filter(Account.owner_id.is_(None)))
            .where(_live(ws))
            .group_by(Account.region)
        )
        .tuples()
        .all()
        if total
    }
    oldest = db.scalar(
        select(func.min(RoutingDecision.decided_at)).where(
            RoutingDecision.workspace_id == ws,
            RoutingDecision.outcome.in_(UNCLAIMED_OUTCOMES),
            RoutingDecision.account_id.in_(list(uncovered & unmatched_90d)),
        )
    )
    waiting_days = round((now - oldest).days) if oldest else 0

    chain = _Chain(
        "territory_gap_strands_accounts",
        "No rule covers the region → nothing matches → the account falls to the triage queue",
        "Region no rule names",
        uncovered,
        "{n} non-customer accounts sit in a region no active routing rule mentions.",
        f"accounts where region not in {sorted(covered_regions)} and segment is not null and is_customer = false",
        covered_regions=sorted(covered_regions),
    )
    chain.step(
        "Routed and unmatched",
        unmatched_90d,
        "{n} of them were routed in the last 90 days and matched nothing.",
        "… and exists (routing_decisions where outcome = 'unmatched' and decided_at >= now() - 90 days)",
        unmatched_by_region=by_region,
    )
    # The A/B count stays a consequence metric rather than a link: an account stranded by a rule gap is
    # stranded whatever its grade, and making the grade a link would delete the whole chain in a dataset
    # where the gap happens to catch no high-fit account.
    chain.step(
        "No owner, no follow-up",
        unowned,
        "{n} still have no owner — triage is where they stopped, not a stage they passed through.",
        "… and owner_id is null",
        oldest_unmatched_days=waiting_days,
        graded_a_or_b=len(chain.ids & unowned & graded_ab),
    )
    high_fit = chain.ids & graded_ab
    return chain.build(
        db,
        consequence={
            "label": "Accounts stranded by a gap in the rule set",
            "accounts": len(chain.ids),
            "sentence": f"{len(chain.ids)} accounts have no territory owner because of a gap in the rule "
            f"set rather than anything about the accounts; {len(high_fit)} of them are graded A or B, and "
            f"the oldest has been waiting {waiting_days} days.",
            "metrics": {
                "high_fit_accounts_stranded": len(high_fit),
                "icp_score_at_risk": _icp_sum(db, chain.ids),
                "open_pipeline_usd": _open_pipeline(db, ws, chain.ids),
                "oldest_unmatched_days": waiting_days,
                "unowned_share_by_region": unowned_rate,
            },
        },
        fix={
            "title": "Give every region a destination, including a catch-all",
            "how": "Add a rule per uncovered region, and one fallback rule with no region condition so a new "
            "region is never silently unroutable.",
            "expected_effect": f"{len(chain.ids)} accounts get an owner immediately, {len(high_fit)} of them "
            "A/B; a fallback rule stops the next new region repeating it.",
            "rec_key": "territory_gap",
        },
        confidence={
            "level": "high",
            "basis": "mechanism + correlation",
            "statement": "The gap is readable in the rule set: no active rule names these regions, and the "
            "unmatched decisions are recorded against exactly those accounts.",
            "limits": "The low ownership rate in these regions is consistent with the gap but not proof of "
            "it — headcount is allocated by region too. The open-pipeline figure is what exists today, not a "
            "forecast of what these accounts would be worth if worked.",
        },
    )


def inspect(db: Session, ws: uuid.UUID) -> dict[str, Any]:
    now = utcnow()
    sections: list[dict[str, Any]] = []
    recs: list[dict[str, Any]] = []
    total_accounts = db.scalar(select(func.count()).select_from(Account).where(_live(ws))) or 1
    dq_open = dict(
        db.execute(
            select(DataQualityIssue.rule_key, func.count())
            .where(DataQualityIssue.workspace_id == ws, DataQualityIssue.status == "open")
            .group_by(DataQualityIssue.rule_key)
        )
        .tuples()
        .all()
    )

    # CRM ---------------------------------------------------------------------------------------------
    sync = operations.sync_health(db, ws, days=7)
    hrs = sync["hours_since_success"]
    crm_status = "critical" if hrs is None or hrs > 48 else _status(sync["record_failure_rate"], 0.02, 0.1)
    sections.append(
        {
            "key": "crm",
            "title": "CRM sync",
            "status": crm_status,
            "headline": (
                "No successful sync on record"
                if hrs is None
                else f"Last successful sync {hrs:.0f}h ago · {sync['record_failure_rate']:.1%} record failures (7d)"
            ),
            "simulated": sync["all_simulated"],
            "evidence": {
                "runs_7d": sync["runs"],
                "failed_runs_7d": sync["failed_runs"],
                "partial_runs_7d": sync["partial_runs"],
                "records_changed_7d": sync["records_changed"],
                "records_failed_7d": sync["records_failed"],
                "retries_7d": sync["retries"],
                "bad_external_ids": dq_open.get("bad_external_id", 0),
                "duplicate_accounts": dq_open.get("duplicate_account", 0),
            },
        }
    )

    # Enrichment --------------------------------------------------------------------------------------
    fields = {
        "domain": Account.domain,
        "industry": Account.industry,
        "employee_count": Account.employee_count,
        "region": Account.region,
        "ai_team_size": Account.ai_team_size,
    }
    field_cov = {
        k: round(
            (db.scalar(select(func.count()).select_from(Account).where(_live(ws), col.is_not(None))) or 0)
            / total_accounts,
            4,
        )
        for k, col in fields.items()
    }
    complete = (
        db.scalar(
            select(func.count()).select_from(Account).where(_live(ws), *[c.is_not(None) for c in fields.values()])
        )
        or 0
    )
    coverage = complete / total_accounts
    providers = operations.provider_health(db, ws)
    stale = dq_open.get("stale_enrichment", 0)
    sections.append(
        {
            "key": "enrichment",
            "title": "Enrichment",
            "status": _status(coverage, 0.9, 0.75, higher_is_worse=False),
            "headline": f"{coverage:.0%} of accounts fully enriched · {1 - coverage:.0%} incomplete · {stale} stale",
            "simulated": all(p["provider"].startswith("demo_") for p in providers),
            "evidence": {
                "accounts": total_accounts,
                "fully_enriched": complete,
                "field_coverage": field_cov,
                "stale_accounts": stale,
                "providers": [
                    {
                        "provider": p["provider"],
                        "hit_rate": p["hit_rate"],
                        "error_rate": p["error_rate"],
                        "cost_credits_30d": p["cost_credits"],
                    }
                    for p in providers
                ],
            },
        }
    )
    missing_core = total_accounts - complete
    if missing_core:
        recs.append(
            {
                "key": "enrichment_waterfall",
                "title": "Schedule the enrichment waterfall for incomplete accounts",
                "impact_accounts": missing_core,
                "priority_accounts": dq_open.get("missing_employee_count", 0),
                "why": f"{missing_core} accounts lack at least one core field "
                f"({', '.join(k for k, v in field_cov.items() if v < 1)}); "
                f"{stale} scored accounts have enrichment older than 180 days.",
                "how": "Nightly workflow: accounts with missing core fields or stale enrichment → enrich_account → "
                "recalculate_score. The waterfall already falls back across providers.",
                "evidence": {"missing_core_fields": missing_core, "stale": stale},
            }
        )

    # Routing -----------------------------------------------------------------------------------------
    since90 = now - timedelta(days=90)
    unmatched = (
        db.execute(
            select(Account.region, func.count(func.distinct(RoutingDecision.account_id)))
            .join(Account, Account.id == RoutingDecision.account_id)
            .where(
                RoutingDecision.workspace_id == ws,
                RoutingDecision.outcome.in_(UNCLAIMED_OUTCOMES),
                RoutingDecision.decided_at >= since90,
            )
            .group_by(Account.region)
        )
        .tuples()
        .all()
    )
    unmatched_by_region = {r or "unknown": n for r, n in unmatched}
    conflicts = (
        db.scalar(
            select(func.count())
            .select_from(RoutingDecision)
            .where(
                RoutingDecision.workspace_id == ws,
                RoutingDecision.decided_at >= since90,
                func.jsonb_array_length(RoutingDecision.conflicts) > 0,
            )
        )
        or 0
    )
    unowned_ab = (
        db.scalar(
            select(func.count())
            .select_from(Account)
            .where(
                _live(ws),
                Account.owner_id.is_(None),
                Account.score_grade.in_(["A", "B"]),
                Account.is_customer.is_(False),
            )
        )
        or 0
    )
    load = analytics.owner_load(db, ws)
    over = [u for u in load if u["is_active"] and u["capacity"] and u["open_accounts"] > u["capacity"]]
    inactive_owned = [u for u in load if not u["is_active"] and u["open_accounts"] > 0]
    lat = operations.routing_latency(db, ws)
    r_status = "critical" if unowned_ab >= 10 else ("warning" if unowned_ab or inactive_owned or over else "healthy")
    sections.append(
        {
            "key": "routing",
            "title": "Routing",
            "status": r_status,
            "headline": (
                f"{unowned_ab} A/B accounts unowned · {sum(unmatched_by_region.values())} unmatched decisions "
                f"(90d) · {conflicts} rule conflicts resolved"
            ),
            "evidence": {
                "unmatched_by_region_90d": unmatched_by_region,
                "conflicts_90d": conflicts,
                "unowned_ab_accounts": unowned_ab,
                "over_capacity_owners": [u["name"] for u in over],
                "inactive_owners_with_accounts": {u["name"]: u["open_accounts"] for u in inactive_owned},
                "median_signal_to_owner_hours": lat["median_signal_to_owner_hours"],
            },
        }
    )
    if unmatched_by_region:
        gap = max(unmatched_by_region.items(), key=lambda kv: kv[1])
        recs.append(
            {
                "key": "territory_gap",
                "title": f"Add a routing rule for {gap[0]}",
                "impact_accounts": sum(unmatched_by_region.values()),
                "priority_accounts": unowned_ab,
                "why": f"{sum(unmatched_by_region.values())} accounts matched no rule in 90 days "
                f"({', '.join(f'{k}: {v}' for k, v in unmatched_by_region.items())}). They land in triage "
                "and stall after replying.",
                "how": f"Add a '{gap[0]} → pool' rule (or a catch-all) so every region has an owner path.",
                "evidence": {"unmatched_by_region": unmatched_by_region, "unowned_ab": unowned_ab},
            }
        )
    if inactive_owned:
        n = sum(u["open_accounts"] for u in inactive_owned)
        recs.append(
            {
                "key": "reassign_departed",
                "title": "Reassign accounts owned by inactive reps",
                "impact_accounts": n,
                "priority_accounts": n,
                "why": f"{n} open accounts are owned by deactivated users "
                f"({', '.join(u['name'] for u in inactive_owned)}).",
                "how": "Re-run routing for those accounts; the engine reassigns when the owner is inactive.",
                "evidence": {"inactive_owners": {u["name"]: u["open_accounts"] for u in inactive_owned}},
            }
        )

    # Data quality ------------------------------------------------------------------------------------
    sev = dict(
        db.execute(
            select(DataQualityIssue.severity, func.count())
            .where(DataQualityIssue.workspace_id == ws, DataQualityIssue.status == "open")
            .group_by(DataQualityIssue.severity)
        )
        .tuples()
        .all()
    )
    sections.append(
        {
            "key": "data_quality",
            "title": "Data quality",
            "status": "critical" if sev.get("high", 0) > 25 else ("warning" if sum(sev.values()) else "healthy"),
            "headline": (
                f"{dq_open.get('duplicate_contact', 0)} duplicate contacts · "
                f"{dq_open.get('missing_employee_count', 0)} accounts missing employee count · "
                f"{sum(dq_open.values())} open issues"
            ),
            "evidence": {"open_by_rule": dq_open, "open_by_severity": sev},
        }
    )
    dupes = dq_open.get("duplicate_contact", 0) + dq_open.get("duplicate_account", 0)
    if dupes:
        recs.append(
            {
                "key": "crm_dedupe",
                "title": "Automate CRM deduplication before sync",
                "impact_accounts": dupes,
                "priority_accounts": dq_open.get("duplicate_account", 0),
                "why": f"{dq_open.get('duplicate_contact', 0)} duplicate contact groups and "
                f"{dq_open.get('duplicate_account', 0)} duplicate account groups split activity history.",
                "how": "Run the dedupe rules on ingest (normalized email/domain) and merge with audit before the "
                "reverse-ETL job; upserting on unique keys prevents new CRM duplicates.",
                "evidence": {
                    "duplicate_contacts": dq_open.get("duplicate_contact", 0),
                    "duplicate_accounts": dq_open.get("duplicate_account", 0),
                },
            }
        )
    lc = dq_open.get("lifecycle_conflict", 0) + dq_open.get("invalid_pipeline_transition", 0)
    if lc:
        recs.append(
            {
                "key": "lifecycle_cleanup",
                "title": "Clean up lifecycle and stage history",
                "impact_accounts": lc,
                "priority_accounts": 0,
                "why": f"{dq_open.get('lifecycle_conflict', 0)} lifecycle conflicts and "
                f"{dq_open.get('invalid_pipeline_transition', 0)} invalid stage transitions distort funnel metrics.",
                "how": "Enforce forward-only lifecycle in the CRM sync mapping and backfill the missing stages.",
                "evidence": {
                    "lifecycle_conflicts": dq_open.get("lifecycle_conflict", 0),
                    "invalid_transitions": dq_open.get("invalid_pipeline_transition", 0),
                },
            }
        )

    # Product signal sync ------------------------------------------------------------------------------
    wh = operations.webhook_health(db, ws, days=7)
    ph_last = wh["last_received"].get("posthog")
    eng_total = db.scalar(select(func.count()).select_from(Engagement).where(Engagement.workspace_id == ws)) or 0
    eng_unmatched = (
        db.scalar(
            select(func.count())
            .select_from(Engagement)
            .where(Engagement.workspace_id == ws, Engagement.account_id.is_(None))
        )
        or 0
    )
    stale_hours = (now - ph_last).total_seconds() / 3600 if ph_last else None
    sections.append(
        {
            "key": "product_signals",
            "title": "Product signal sync",
            "status": "critical" if stale_hours is None or stale_hours > 24 else _status(wh["failure_rate"], 0.02, 0.1),
            "headline": (
                f"Last product event {stale_hours:.0f}h ago · {wh['failure_rate']:.1%} webhook failures (7d) · "
                f"{eng_unmatched} unmatched events"
                if stale_hours is not None
                else "No product events received"
            ),
            "evidence": {
                "webhooks_7d": wh["total"],
                "failure_rate_7d": wh["failure_rate"],
                "duplicates_absorbed_7d": wh["duplicates_absorbed"],
                "engagement_events": eng_total,
                "unmatched_events": eng_unmatched,
            },
        }
    )
    pql = db.execute(
        select(Signal.account_id, Signal.observed_at).where(
            Signal.workspace_id == ws,
            Signal.signal_type == "usage_threshold",
            Signal.observed_at >= now - timedelta(days=60),
        )
    ).all()
    slow = 0
    for acc, at in pql:
        touched = (
            db.scalar(
                select(func.count())
                .select_from(Activity)
                .where(
                    Activity.account_id == acc,
                    Activity.occurred_at >= at,
                    Activity.occurred_at <= at + timedelta(days=3),
                    Activity.type.in_(["email_sent", "task", "meeting_booked", "call"]),
                )
            )
            or 0
        )
        slow += 0 if touched else 1
    if slow:
        recs.append(
            {
                "key": "pql_routing",
                "title": "Route product-qualified accounts within one business day",
                "impact_accounts": slow,
                "priority_accounts": slow,
                "why": f"{slow} of {len(pql)} accounts that crossed the usage threshold in 60 days had no sales "
                "touch within 3 days.",
                "how": "Enable the 'Product-qualified account → AE' workflow (route + task + lifecycle) on the "
                "usage_threshold event.",
                "evidence": {"pql_accounts_60d": len(pql), "untouched_within_3d": slow},
            }
        )

    # Buying-signal coverage ---------------------------------------------------------------------------
    hot = db.execute(
        select(Signal.account_id, func.max(Signal.observed_at))
        .join(Account, Account.id == Signal.account_id)
        .where(
            Signal.workspace_id == ws,
            Signal.signal_type.in_(["funding_round", "ai_product_launch", "executive_hire", "ai_hiring_surge"]),
            Signal.observed_at >= now - timedelta(days=14),
            Account.score_grade.in_(["A", "B"]),
        )
        .group_by(Signal.account_id)
    ).all()
    untouched = 0
    for acc, at in hot:
        t = (
            db.scalar(
                select(func.count())
                .select_from(Activity)
                .where(
                    Activity.account_id == acc,
                    Activity.occurred_at >= at - timedelta(days=1),
                    Activity.type.in_(["email_sent", "task", "meeting_booked"]),
                )
            )
            or 0
        )
        untouched += 0 if t else 1
    if untouched:
        recs.append(
            {
                "key": "buying_signal_workflow",
                "title": "Act on fresh buying signals automatically",
                "impact_accounts": untouched,
                "priority_accounts": untouched,
                "why": f"{untouched} A/B accounts had a funding, launch, executive or hiring signal in the "
                "last 14 days with no outreach since.",
                "how": "The 'Funding signal → research → outreach draft' workflow drafts evidence-grounded outreach "
                "into the approval queue within minutes of the signal.",
                "evidence": {"ab_accounts_with_fresh_signals": len(hot), "no_touch_since_signal": untouched},
            }
        )

    # Attribution --------------------------------------------------------------------------------------
    attr = run_attribution(db, ws, days=180)
    unattr_share = (attr["unattributed_opportunities"] / attr["opportunities"]) if attr["opportunities"] else 0
    sections.append(
        {
            "key": "attribution",
            "title": "Attribution",
            "status": _status(unattr_share, 0.15, 0.35),
            "headline": f"Incomplete for {unattr_share:.0%} of opportunities (180d)",
            "evidence": {
                "opportunities_180d": attr["opportunities"],
                "unattributed_opportunities": attr["unattributed_opportunities"],
                "unattributed_pipeline": attr["unattributed_pipeline"],
            },
        }
    )

    # Workflows ----------------------------------------------------------------------------------------
    wf = operations.workflow_health(db, ws, days=30)
    sections.append(
        {
            "key": "workflows",
            "title": "Automation reliability",
            "status": _status(wf["failure_rate"], 0.03, 0.1),
            "headline": (
                f"{wf['failure_rate']:.1%} of executed runs failed (30d) · {wf['dead_letter_total']} in dead letter · "
                f"{wf['retried_steps']} steps recovered by retry"
            ),
            "evidence": {
                "by_status_30d": wf["by_status"],
                "dead_letter_total": wf["dead_letter_total"],
                "retried_steps_30d": wf["retried_steps"],
            },
        }
    )

    # Outbound hygiene ---------------------------------------------------------------------------------
    since30 = now - timedelta(days=30)
    sent = (
        db.scalar(
            select(func.count())
            .select_from(Activity)
            .where(Activity.workspace_id == ws, Activity.type == "email_sent", Activity.occurred_at >= since30)
        )
        or 0
    )
    bounced = (
        db.scalar(
            select(func.count())
            .select_from(Activity)
            .where(Activity.workspace_id == ws, Activity.type == "email_bounced", Activity.occurred_at >= since30)
        )
        or 0
    )
    invalid_contacts = (
        db.scalar(
            select(func.count())
            .select_from(Contact)
            .where(
                Contact.workspace_id == ws,
                Contact.merged_into_id.is_(None),
                Contact.email_status == "invalid",
                Contact.do_not_contact.is_(False),
            )
        )
        or 0
    )
    bounce = bounced / sent if sent else 0.0
    sections.append(
        {
            "key": "outbound",
            "title": "Outbound hygiene",
            "status": _status(bounce, 0.02, 0.05),
            "headline": f"{bounce:.1%} bounce rate (30d) · {invalid_contacts} invalid emails not suppressed",
            "evidence": {
                "sent_30d": sent,
                "bounced_30d": bounced,
                "invalid_unsuppressed": invalid_contacts,
                "note": "Deliverability also depends on SPF/DKIM/DMARC and domain warm-up, which GTMOS "
                "does not manage.",
            },
        }
    )

    stuck = analytics.stuck_accounts(db, ws)
    open_opps_idle = (
        db.scalar(
            select(func.count())
            .select_from(Opportunity)
            .where(Opportunity.workspace_id == ws, Opportunity.stage.in_(analytics.OPEN_DEAL))
        )
        or 0
    )
    recs.sort(key=lambda r: (-r["priority_accounts"], -r["impact_accounts"]))
    for i, r in enumerate(recs, start=1):
        r["rank"] = i
    overall = max((s["status"] for s in sections), key=lambda s: STATUS_ORDER[s])
    return {
        "generated_at": now,
        "overall_status": overall,
        "summary": {
            "healthy": sum(s["status"] == "healthy" for s in sections),
            "warning": sum(s["status"] == "warning" for s in sections),
            "critical": sum(s["status"] == "critical" for s in sections),
        },
        "sections": sections,
        "causal_chains": causal_chains(db, ws, now),
        "recommendations": recs,
        "context": {
            "stuck_accounts": stuck["total"],
            "stuck_by_stage": stuck["by_stage"],
            "open_opportunities": open_opps_idle,
        },
        "method": "Every status and recommendation is computed from live queries at request time; "
        "thresholds are defined in services/stack_inspector.py.",
    }
