"""python -m gtmos.demonumbers [--json] [--out PATH]

Renders the demo dataset's headline figures as committed markdown.

These numbers — the routing SLA report, the seeded experiment's result, the data-quality counts and
the deliverability assessment — used to be typed by hand into the README and the concept docs. They
describe a rolling ninety-day window over a dataset that is reseeded, so they go stale within weeks
and the reader discovers it by opening the page the README just sent them to. Three of them had
drifted far enough that the README claimed the system was *better* than the running app showed.

The scoring backtest and the content-evaluation report already solved this by generating their own
reports. This is the same fix applied to the last hand-typed block: prose cites this file, this file
is regenerated by `make docs-numbers`, and a stale figure becomes a diff instead of a discovery.

Reads only; it never writes to the database.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import func, select

from gtmos.db import session_scope
from gtmos.models import DataQualityIssue, Experiment, Workspace
from gtmos.services import data_quality, deliverability_service, experiments_service, routing_service

WINDOW_DAYS = 90
FEATURED_EXPERIMENT = "provocative-subject"


def _pct(x: float | None, places: int = 2) -> str:
    """None-tolerant: a service that legitimately has no value for a signal should render as "—",
    not crash the generator and leave the committed file stale — which is the exact failure this
    file exists to prevent."""
    if x is None:
        return "—"
    return f"{x * 100:.{places}f}%"


def _ci(low: float | None, high: float | None) -> str:
    """A list-composition signal is a census, not a sample, so it carries no interval. Rendering
    "—" beats rendering an em-dash range that looks like a broken number."""
    if low is None or high is None:
        return "—"
    return f"{_pct(low)}–{_pct(high)}"


def collect(db: Any, ws_id: Any) -> dict[str, Any]:
    sla = routing_service.sla_report(db, ws_id, days=WINDOW_DAYS)

    counts = db.execute(
        select(DataQualityIssue.rule_key, func.count())
        .where(DataQualityIssue.workspace_id == ws_id, DataQualityIssue.status == "open")
        .group_by(DataQualityIssue.rule_key)
    ).all()
    by_rule = dict(counts)

    exp = db.scalar(select(Experiment).where(Experiment.workspace_id == ws_id, Experiment.key == FEATURED_EXPERIMENT))
    experiment = experiments_service.results(db, exp) if exp else None

    return {
        # Deliberately not stamped into the rendered file. A timestamp makes every regeneration a
        # diff, which trains the reader to ignore the diff — and the whole point of committing this
        # file is that a *figure* changing shows up in review. Git already records when it changed.
        "generated_at": datetime.now(UTC).isoformat(),
        "window_days": WINDOW_DAYS,
        "routing_sla": sla,
        "data_quality": {
            "open_total": sum(by_rule.values()),
            "rule_count": len(data_quality.RULES),
            "by_rule": by_rule,
        },
        "experiment": experiment,
        "deliverability": deliverability_service.assess(db, ws_id, WINDOW_DAYS),
    }


def _sla_section(sla: dict[str, Any]) -> list[str]:
    total = sla.get("decisions_with_sla", 0)
    return [
        "## Routing SLA",
        "",
        f"Over the last {WINDOW_DAYS} days, **{total}** lead-event assignments carry an SLA.",
        "",
        "| Measure | Value |",
        "| --- | ---: |",
        f"| Assignments with an SLA | {total} |",
        f"| Met the SLA | {sla.get('met', 0)} ({_pct(sla.get('hit_rate', 0.0), 1)} of those decided) |",
        f"| Touched late | {sla.get('late', 0)} |",
        f"| Never touched at all | {sla.get('untouched', 0)} |",
        f"| Still pending (clock running) | {sla.get('pending', 0)} |",
        f"| Median time to first touch | {sla.get('median_hours_to_first_touch') or 0:.1f} h |",
        "",
        "**Late**, **never touched** and **pending** are counted separately on purpose. A late touch is "
        "a process problem; an assignment nobody ever touched is a lead that was routed into silence; "
        "and an assignment whose clock is still running is neither. Collapsing the three hides the "
        "second inside the first and inflates the hit rate with the third.",
    ]


def _dq_section(dq: dict[str, Any]) -> list[str]:
    rows = sorted(dq["by_rule"].items(), key=lambda kv: -kv[1])
    lines = [
        "## Data quality",
        "",
        f"**{dq['open_total']}** open issues across **{dq['rule_count']}** rules.",
        "",
        "| Rule | Open |",
        "| --- | ---: |",
    ]
    lines += [f"| `{k}` | {n} |" for k, n in rows]
    lines += [
        "",
        "`provider_conflict` is the one worth reading: those are fields where two providers materially "
        "disagree and GTMOS refused to pick a winner on confidence alone. It raises an issue instead, "
        "which is a deliberately worse experience than silently overwriting and a much better outcome.",
    ]
    return lines


def _experiment_section(exp: dict[str, Any] | None) -> list[str]:
    """Render the featured experiment straight from `experiments_service.results`.

    The shapes here are the service's own: `variants` is a list keyed by `key` with a `metrics` dict
    per variant, and `comparisons` / `guardrails` are keyed by the non-control variant. Reading them
    rather than restating them is the whole point of this file.
    """
    if not exp:
        return ["## Experiment: provocative subject", "", "_Not present in this dataset._"]

    primary = exp.get("primary_metric", "reply")
    by_key = {v["key"]: v for v in exp.get("variants", [])}
    control = next((v for v in exp.get("variants", []) if v.get("is_control")), None)
    treatment_key = next((k for k in exp.get("comparisons", {})), None)
    if control is None or treatment_key is None:
        return ["## Experiment: provocative subject", "", "_Incomplete result in this dataset._"]
    treatment = by_key[treatment_key]
    cmp_ = exp["comparisons"][treatment_key].get(primary, {})

    def rate(v: dict[str, Any], metric: str) -> str:
        m = (v.get("metrics") or {}).get(metric) or {}
        return f"{_pct(m.get('rate', 0.0))} (n={m.get('n', 0)})"

    lines = [
        "## Experiment: provocative subject",
        "",
        f"Verdict **{exp.get('verdict', 'unknown')}** — recommendation: "
        f"**{(exp.get('recommendation') or {}).get('action', 'unknown')}**.",
        "",
        "| Metric | Control | Treatment | Verdict |",
        "| --- | ---: | ---: | --- |",
        f"| **{primary}** (primary) | {rate(control, primary)} | {rate(treatment, primary)} | "
        f"{cmp_.get('absolute_lift', 0.0) * 100:+.1f} pp, p = {cmp_.get('p_value', float('nan')):.2e} |",
    ]
    for metric, g in (exp.get("guardrails", {}).get(treatment_key, {}) or {}).items():
        c, t = g.get("control") or {}, g.get("treatment") or {}
        lines.append(
            f"| {g.get('label', metric)} (guardrail) | {_pct(c.get('rate', 0.0))} | "
            f"{_pct(t.get('rate', 0.0))} (95% CI {_pct(t.get('ci_low', 0.0))}–{_pct(t.get('ci_high', 0.0))}) | "
            f"{'**' + str(g.get('status')) + '**' if g.get('status') != 'ok' else 'ok'} |"
        )
    lines += [
        "",
        "This is the case the experiment engine exists for: the treatment wins the primary metric "
        "decisively and is still rejected, because a guardrail breached. A system that ships the "
        "winner here is a system that burns the list.",
    ]
    return lines


def _deliverability_section(d: dict[str, Any]) -> list[str]:
    risk = d.get("risk") or {}
    lines = [
        "## Deliverability",
        "",
        f"Risk score **{risk.get('risk_score')}/100**, verdict **{risk.get('verdict')}** — {risk.get('headline', '')}",
        "",
        "| Signal | Rate | 95% CI | Status | Proven? |",
        "| --- | ---: | :---: | --- | --- |",
    ]
    for sig in risk.get("signals", []):
        lines.append(
            f"| {sig.get('label', sig.get('metric'))} | {_pct(sig.get('rate', 0.0))} | "
            f"{_ci(sig.get('ci_low'), sig.get('ci_high'))} | {sig.get('status')} | "
            f"{'yes' if sig.get('proven') else 'not proven'} |"
        )
    lines += [
        "",
        "The **Proven?** column is the point. A rate over its threshold whose confidence interval still "
        "reaches back under it is *not proven and not ignorable*, and the assessment says so rather "
        "than rounding a wide interval into a verdict.",
        "",
        "GTMOS has no mailbox and sends nothing. These are inputs to a capacity calculator and a list-"
        "health assessment, not a description of infrastructure that exists.",
    ]
    return lines


def render(report: dict[str, Any]) -> str:
    lines = [
        "# Demo dataset figures",
        "",
        "**Generated by `make docs-numbers`. Do not edit by hand.**",
        "",
        "These are the headline figures the README and the concept docs refer to. They describe a "
        f"rolling {WINDOW_DAYS}-day window over a synthetic dataset, so they move when the data is "
        "reseeded — which is exactly why they live in a generated file rather than in prose. If a "
        "number here disagrees with something written elsewhere in the repository, this file is right "
        "and the prose is stale.",
        "",
        "**The dataset is synthetic.** Nothing below describes real customers, real sending, or real outcomes.",
        "",
        "---",
        "",
    ]
    rule = ["", "---", ""]
    lines += [*_sla_section(report["routing_sla"]), *rule]
    lines += [*_experiment_section(report["experiment"]), *rule]
    lines += [*_dq_section(report["data_quality"]), *rule]
    lines += _deliverability_section(report["deliverability"])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="emit the raw report instead of markdown")
    parser.add_argument("--out", type=Path, help="write to this path instead of stdout")
    args = parser.parse_args()

    with session_scope() as db:
        ws = db.scalar(select(Workspace).order_by(Workspace.created_at))
        if ws is None:
            print("No workspace found. Run `make seed` first.", file=sys.stderr)
            return 1
        report = collect(db, ws.id)

    text = json.dumps(report, indent=2, default=str) if args.json else render(report)
    if args.out:
        args.out.write_text(text + "\n")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
